In [26]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
ccdb=pd.read_csv("UCI_Credit_Card.csv")

ccdb.shape

(30000, 25)

In [3]:
#nice way to look at some of data
ccdb.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
ID,30000.0,15000.500000,8660.398374,1.0,7500.75,15000.5,22500.25,30000.0
LIMIT_BAL,30000.0,167484.322667,129747.661567,10000.0,50000.00,140000.0,240000.00,1000000.0
SEX,30000.0,1.603733,0.489129,1.0,1.00,2.0,2.00,2.0
EDUCATION,30000.0,1.853133,0.790349,0.0,1.00,2.0,2.00,6.0
MARRIAGE,30000.0,1.551867,0.521970,0.0,1.00,2.0,2.00,3.0
AGE,30000.0,35.485500,9.217904,21.0,28.00,34.0,41.00,79.0
PAY_0,30000.0,-0.016700,1.123802,-2.0,-1.00,0.0,0.00,8.0
PAY_2,30000.0,-0.133767,1.197186,-2.0,-1.00,0.0,0.00,8.0
PAY_3,30000.0,-0.166200,1.196868,-2.0,-1.00,0.0,0.00,8.0
PAY_4,30000.0,-0.220667,1.169139,-2.0,-1.00,0.0,0.00,8.0
PAY_5,30000.0,-0.266200,1.133187,-2.0,-1.00,0.0,0.00,8.0
PAY_6,30000.0,-0.291100,1.149988,-2.0,-1.00,0.0,0.00,8.0
BILL_AMT1,30000.0,51223.330900,73635.860576,-165580.0,3558.75,22381.5,67091.00,964511.0
BILL_AMT2,30000.0,49179.075167,71173.768783,-69777.0,2984.75,21200.0,64006.25,983931.0
BILL_AMT3,30000.0,47013.154800,69349.387427,-157264.0,2666.25,20088.5,60164.75,1664089.0
BILL_AMT4,30000.0,43262.948967,64332.856134,-170000.0,2326.75,19052.0,54506.00,891586.0
BILL_AMT5,30000.0,40311.400967,60797.155770,-81334.0,1763.00,18104.5,50190.50,927171.0
BILL_AMT6,30000.0,38871.760400,59554.107537,-339603.0,1256.00,17071.0,49198.25,961664.0
PAY_AMT1,30000.0,5663.580500,16563.280354,0.0,1000.00,2100.0,5006.00,873552.0
PAY_AMT2,30000.0,5921.163500,23040.870402,0.0,833.00,2009.0,5000.00,1684259.0
PAY_AMT3,30000.0,5225.681500,17606.961470,0.0,390.00,1800.0,4505.00,896040.0
PAY_AMT4,30000.0,4826.076867,15666.159744,0.0,296.00,1500.0,4013.25,621000.0
PAY_AMT5,30000.0,4799.387633,15278.305679,0.0,252.50,1500.0,4031.50,426529.0
PAY_AMT6,30000.0,5215.502567,17777.465775,0.0,117.75,1500.0,4000.00,528666.0
default.payment.next.month,30000.0,0.221200,0.415062,0.0,0.00,0.0,0.00,1.0

In [5]:
x = ccdb.drop("default.payment.next.month", axis=1)
y = ccdb["default.payment.next.month"]

In [6]:
#split data into training and testing data
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.25, random_state=1693)

#transform and fit the data
scale_x = StandardScaler()
x_train = scale_x.fit_transform(x_train)
x_test = scale_x. transform(x_test)

In [8]:
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix

#three hidden layers of 13 nodes each
mlp = MLPClassifier(hidden_layer_sizes=(13,13,13), max_iter=500)

In [10]:
#fit the neural network to the training data, and use the fitted network to make a prediction
mlp.fit(x_train, y_train)
pred = mlp.predict(x_test)
#print(pred)

In [11]:
#this is a prediction of default (1) or not defaulting (0)
pred

array([1, 0, 0, ..., 1, 0, 0])

In [12]:
nn_cm = confusion_matrix(y_test, pred)
#print(nn_cm)
#nn_cm

array([[5540,  322],
       [1040,  598]])

In [13]:
print_cm(nn_cm, ["No Default", "Default"])

NameError: name 'print_cm' is not defined

In [21]:

from cmPrint import print_cm

In [22]:
print_cm(nn_cm, ["No Default", "Default"])
#false positive in bottom left

               No Default    Default
    No Default     5540.0      322.0
       Default     1040.0      598.0

In [23]:
updated_mlp = MLPClassifier(hidden_layer_sizes=(10,20,10),
                            activation='tanh',
                            solver="sgd",
                            batch_size=200,
                            learning_rate="adaptive",
                            max_iter=500,
                            verbose=True
                            )

updated_mlp.fit(x_train, y_train)

Iteration 1, loss = 0.57310387
Iteration 2, loss = 0.50020313
Iteration 3, loss = 0.48528963
Iteration 4, loss = 0.47658371
Iteration 5, loss = 0.47049840
Iteration 6, loss = 0.46602039
Iteration 7, loss = 0.46254484
Iteration 8, loss = 0.45975598
Iteration 9, loss = 0.45745827
Iteration 10, loss = 0.45549281
Iteration 11, loss = 0.45384430
Iteration 12, loss = 0.45243578
Iteration 13, loss = 0.45124007
Iteration 14, loss = 0.45015438
Iteration 15, loss = 0.44919992
Iteration 16, loss = 0.44841401
Iteration 17, loss = 0.44766933
Iteration 18, loss = 0.44699600
Iteration 19, loss = 0.44638297
Iteration 20, loss = 0.44584468
Iteration 21, loss = 0.44531371
Iteration 22, loss = 0.44486702
Iteration 23, loss = 0.44441698
Iteration 24, loss = 0.44398197
Iteration 25, loss = 0.44360443
Iteration 26, loss = 0.44319321
Iteration 27, loss = 0.44283858
Iteration 28, loss = 0.44250082
Iteration 29, loss = 0.44215619
Iteration 30, loss = 0.44186419
Iteration 31, loss = 0.44158130
Iteration 32, loss = 0.44130031
Iteration 33, loss = 0.44104114
Iteration 34, loss = 0.44076323
Iteration 35, loss = 0.44054131
Iteration 36, loss = 0.44030653
Iteration 37, loss = 0.44004483
Iteration 38, loss = 0.43983143
Iteration 39, loss = 0.43962214
Iteration 40, loss = 0.43943442
Iteration 41, loss = 0.43921031
Iteration 42, loss = 0.43903955
Iteration 43, loss = 0.43881639
Iteration 44, loss = 0.43864268
Iteration 45, loss = 0.43847903
Iteration 46, loss = 0.43828805
Iteration 47, loss = 0.43812628
Iteration 48, loss = 0.43796814
Iteration 49, loss = 0.43778537
Iteration 50, loss = 0.43760252
Iteration 51, loss = 0.43747433
Iteration 52, loss = 0.43733285
Iteration 53, loss = 0.43715152
Iteration 54, loss = 0.43699603
Iteration 55, loss = 0.43687334
Iteration 56, loss = 0.43672244
Iteration 57, loss = 0.43658210
Iteration 58, loss = 0.43643031
Iteration 59, loss = 0.43629185
Iteration 60, loss = 0.43614863
Iteration 61, loss = 0.43601942
Iteration 62, loss = 0.43591706
Iteration 63, loss = 0.43576690
Iteration 64, loss = 0.43564896
Iteration 65, loss = 0.43550095
Iteration 66, loss = 0.43537539
Iteration 67, loss = 0.43526192
Iteration 68, loss = 0.43515860
Iteration 69, loss = 0.43502150
Iteration 70, loss = 0.43489591
Iteration 71, loss = 0.43476427
Iteration 72, loss = 0.43470420
Iteration 73, loss = 0.43453379
Iteration 74, loss = 0.43443747
Iteration 75, loss = 0.43435633
Iteration 76, loss = 0.43426032
Training loss did not improve more than tol=0.000100 for two consecutive epochs. Setting learning rate to 0.000200
Iteration 77, loss = 0.43404476
Iteration 78, loss = 0.43401096
Iteration 79, loss = 0.43398468
Iteration 80, loss = 0.43397430
Training loss did not improve more than tol=0.000100 for two consecutive epochs. Setting learning rate to 0.000040
Iteration 81, loss = 0.43392405
Iteration 82, loss = 0.43392015
Iteration 83, loss = 0.43391571
Training loss did not improve more than tol=0.000100 for two consecutive epochs. Setting learning rate to 0.000008
Iteration 84, loss = 0.43390757
Iteration 85, loss = 0.43390693
Iteration 86, loss = 0.43390583
Training loss did not improve more than tol=0.000100 for two consecutive epochs. Setting learning rate to 0.000002
Iteration 87, loss = 0.43390436
Iteration 88, loss = 0.43390420
Iteration 89, loss = 0.43390399
Training loss did not improve more than tol=0.000100 for two consecutive epochs. Setting learning rate to 0.000000
Iteration 90, loss = 0.43390368
Iteration 91, loss = 0.43390363
Iteration 92, loss = 0.43390360
Training loss did not improve more than tol=0.000100 for two consecutive epochs. Learning rate too small. Stopping.

MLPClassifier(activation='tanh', alpha=0.0001, batch_size=200, beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(10, 20, 10), learning_rate='adaptive',
       learning_rate_init=0.001, max_iter=500, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='sgd', tol=0.0001, validation_fraction=0.1,
       verbose=True, warm_start=False)

In [24]:
pred = updated_mlp.predict(x_test)
nn_cm = confusion_matrix(y_test, pred)
print_cm(nn_cm, ["No Default", "Default"])

               No Default    Default
    No Default     5542.0      320.0
       Default     1059.0      579.0